# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Francisco Ripoli's Blog
tagline:          A blog about tech and general stuff
description:      Blog's Description
url:              http://xico.ripoli.com.br
paginate:         5

author:
  name:           'Francisco Ripoli'
  url:            https://twitter.com/xicoripoli

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/fripoli
